# Игровые константы
PLAYER_STAMINA_MAX = 120
STAMINA_DRAIN_RATE = 1.2
STAMINA_REGEN_RATE = 0.4
FIRE_DRAIN_RATE = 0.02
FIRE_SNOW_PENALTY = 0.02
TREE_HP_MIN = 3
TREE_HP_MAX = 5
FOOTPRINT_LIFETIME = 800
SNOW_DRAIN_MULTIPLIER = 2
INTERACTION_COOLDOWN = 50
FOOTPRINT_SPAWN_INTERVAL = 20

# Размеры
TREE_COLLISION_WIDTH = 4 * 3
TREE_COLLISION_HEIGHT = 2 * 3
TREE_INTERACTION_WIDTH = 10 * 3
TREE_INTERACTION_HEIGHT = 8 * 3
PLAYER_COLLISION_WIDTH = 4 * 3
PLAYER_COLLISION_HEIGHT = 3 * 3

# Отступы и позиции
PLAYER_SPRITE_OFFSET_X = 1 * 3
PLAYER_SPRITE_OFFSET_Y = 6 * 3
PLAYER_RECT_OFFSET_Y = 7 * 3

# Цвета
COLOR_BLUE_DARK = (0, 103, 155)
COLOR_BLUE_LIGHT = (0, 203, 255)
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0, 0, 255)

# Анимация
PLAYER_ANIMATION_FRAMES = 10
FIRE_ANIMATION_STEP = 10
SNOW_ANIMATION_STEP = 10

# Погода
SNOW_CYCLE_DURATION = 150
SNOW_DURATION_MULTIPLIER = 75
SNOW_ALPHA_MIN = 0
SNOW_ALPHA_MAX = 255

# Генерация мира
TREES_PER_SCREEN = 200
TREE_SPACING_THRESHOLD = 48
TREE_MIN_DISTANCE_FROM_CENTER = 200
SPATIAL_GRID_SIZE = 24

# Интерфейс
INTERFACE_BAR_WIDTH = 200
INTERFACE_BAR_HEIGHT = 20
FPS_DISPLAY_X = 35
STATISTICS_FILE = 'statistics.txt'